### ISSUE TITLE
Kafa-minion pods in CrashLoop when trying to connect to Confluent Operator Kafka

### ISSUE THREAD

**Issue by kanuahs** [cloudworkz/kafka-minion#68]
Other services can connect and use this Kafka cluster. I'm using the Helm chart.
Versions:
- Confluent-operator : `5.5.1`
- Kafka-minion : `v1.0.2` (Chart version: `v1.3.0`)
Here are the logs:
Kafka logs:
```
   [Clear CT: 1.0 ms]
   [Other: 4.2 ms]
      [Choose CSet: 0.0 ms]
      [Ref Proc: 0.3 ms]
      [Ref Enq: 0.0 ms]
      [Redirty Cards: 0.3 ms]
      [Humongous Register: 0.5 ms]
      [Humongous Reclaim: 0.1 ms]
      [Free CSet: 2.4 ms]
   [Eden: 3681.0M(3681.0M)->0.0B(3676.0M) Survivors: 5120.0K->10.0M Heap: 3851.9M(6144.0M)->175.9M(6144.0M)]
 [Times: user=0.04 sys=0.01, real=0.01 secs] 
[INFO] 2020-11-08 16:17:09,839 [data-plane-kafka-network-thread-0-ListenerName(INTERNAL)-SASL_PLAINTEXT-0] org.apache.kafka.common.network.Selector pollSelectionKeys - [SocketServer brokerId=0] Failed authentication with /10.30.226.28 (Unexpected Kafka request of type METADATA during SASL handshake.)
[INFO] 2020-11-08 16:17:10,393 [data-plane-kafka-network-thread-0-ListenerName(INTERNAL)-SASL_PLAINTEXT-2] org.apache.kafka.common.network.Selector pollSelectionKeys - [SocketServer brokerId=0] Failed authentication with /10.30.226.28 (Unexpected Kafka request of type METADATA during SASL handshake.)
[INFO] 2020-11-08 16:17:16,484 [data-plane-kafka-network-thread-0-ListenerName(INTERNAL)-SASL_PLAINTEXT-3] org.apache.kafka.common.network.Selector pollSelectionKeys - [SocketServer brokerId=0] Failed authentication with /10.30.225.21 (Unexpected Kafka request of type METADATA during SASL handshake.)
[INFO] 2020-11-08 16:17:17,040 [data-plane-kafka-network-thread-0-ListenerName(INTERNAL)-SASL_PLAINTEXT-0] org.apache.kafka.common.network.Selector pollSelectionKeys - [SocketServer brokerId=0] Failed authentication with /10.30.225.21 (Unexpected Kafka request of type METADATA during SASL handshake.)
[INFO] 2020-11-08 16:17:17,594 [data-plane-kafka-network-thread-0-ListenerName(INTERNAL)-SASL_PLAINTEXT-1] org.apache.kafka.common.network.Selector pollSelectionKeys - [SocketServer brokerId=0] Failed authentication with /10.30.225.21 (Unexpected Kafka request of type METADATA during SASL handshake.)
[INFO] 2020-11-08 16:17:18,148 [data-plane-kafka-network-thread-0-ListenerName(INTERNAL)-SASL_PLAINTEXT-2] org.apache.kafka.common.network.Selector pollSelectionKeys - [SocketServer brokerId=0] Failed authentication with /10.30.225.21 (Unexpected Kafka request of type METADATA during SASL handshake.)
[INFO] 2020-11-08 16:17:21,421 [data-plane-kafka-network-thread-0-ListenerName(INTERNAL)-SASL_PLAINTEXT-0] org.apache.kafka.common.network.Selector pollSelectionKeys - [SocketServer brokerId=0] Failed authentication with /10.30.226.28 (Unexpected Kafka request of type METADATA during SASL handshake.)
[INFO] 2020-11-08 16:17:21,974 [data-plane-kafka-network-thread-0-ListenerName(INTERNAL)-SASL_PLAINTEXT-1] org.apache.kafka.common.network.Selector pollSelectionKeys - [SocketServer brokerId=0] Failed authentication with /10.30.226.28 (Unexpected Kafka request of type METADATA during SASL handshake.)
[INFO] 2020-11-08 16:17:22,528 [data-plane-kafka-network-thread-0-ListenerName(INTERNAL)-SASL_PLAINTEXT-2] org.apache.kafka.common.network.Selector pollSelectionKeys - [SocketServer brokerId=0] Failed authentication with /10.30.226.28 (Unexpected Kafka request of type METADATA during SASL handshake.)
[INFO] 2020-11-08 16:17:23,081 [data-plane-kafka-network-thread-0-ListenerName(INTERNAL)-SASL_PLAINTEXT-3] org.apache.kafka.common.network.Selector pollSelectionKeys - [SocketServer brokerId=0] Failed authentication with /10.30.226.28 (Unexpected Kafka request of type METADATA during SASL handshake.)
[INFO] 2020-11-08 16:17:44,708 [data-plane-kafka-network-thread-0-ListenerName(INTERNAL)-SASL_PLAINTEXT-3] org.apache.kafka.common.network.Selector pollSelectionKeys - [SocketServer brokerId=0] Failed authentication with /10.30.226.28 (Unexpected Kafka request of type METADATA during SASL handshake.)
[INFO] 2020-11-08 16:17:45,261 [data-plane-kafka-network-thread-0-ListenerName(INTERNAL)-SASL_PLAINTEXT-0] org.apache.kafka.common.network.Selector pollSelectionKeys - [SocketServer brokerId=0] Failed authentication with /10.30.226.28 (Unexpected Kafka request of type METADATA during SASL handshake.)
[INFO] 2020-11-08 16:17:45,815 [data-plane-kafka-network-thread-0-ListenerName(INTERNAL)-SASL_PLAINTEXT-1] org.apache.kafka.common.network.Selector pollSelectionKeys - [SocketServer brokerId=0] Failed authentication with /10.30.226.28 (Unexpected Kafka request of type METADATA during SASL handshake.)
[INFO] 2020-11-08 16:17:46,368 [data-plane-kafka-network-thread-0-ListenerName(INTERNAL)-SASL_PLAINTEXT-2] org.apache.kafka.common.network.Selector pollSelectionKeys - [SocketServer brokerId=0] Failed authentication with /10.30.226.28 (Unexpected Kafka request of type METADATA during SASL handshake.)
[INFO] 2020-11-08 16:18:33,725 [data-plane-kafka-network-thread-0-ListenerName(INTERNAL)-SASL_PLAINTEXT-1] org.apache.kafka.common.network.Selector pollSelectionKeys - [SocketServer brokerId=0] Failed authentication with /10.30.226.28 (Unexpected Kafka request of type METADATA during SASL handshake.)
[INFO] 2020-11-08 16:18:34,278 [data-plane-kafka-network-thread-0-ListenerName(INTERNAL)-SASL_PLAINTEXT-2] org.apache.kafka.common.network.Selector pollSelectionKeys - [SocketServer brokerId=0] Failed authentication with /10.30.226.28 (Unexpected Kafka request of type METADATA during SASL handshake.)
[INFO] 2020-11-08 16:18:34,907 [data-plane-kafka-network-thread-0-ListenerName(INTERNAL)-SASL_PLAINTEXT-3] org.apache.kafka.common.network.Selector pollSelectionKeys - [SocketServer brokerId=0] Failed authentication with /10.30.226.28 (Unexpected Kafka request of type METADATA during SASL handshake.)
[INFO] 2020-11-08 16:18:35,460 [data-plane-kafka-network-thread-0-ListenerName(INTERNAL)-SASL_PLAINTEXT-0] org.apache.kafka.common.network.Selector pollSelectionKeys - [SocketServer brokerId=0] Failed authentication with /10.30.226.28 (Unexpected Kafka request of type METADATA during SASL handshake.)
[INFO] 2020-11-08 16:18:45,550 [data-plane-kafka-network-thread-0-ListenerName(INTERNAL)-SASL_PLAINTEXT-3] org.apache.kafka.common.network.Selector pollSelectionKeys - [SocketServer brokerId=0] Failed authentication with /10.30.225.21 (Unexpected Kafka request of type METADATA during SASL handshake.)
```

Kafka-minion logs
```
{"level":"info","msg":"Starting kafka minion version1.0.2","time":"2020-11-08T16:17:44Z"}
{"level":"debug","msg":"Sarama client config has been created successfully","time":"2020-11-08T16:17:44Z"}
{"address":"<KAFKA_URL>:9071","level":"info","module":"cluster","msg":"connecting to kafka cluster","time":"2020-11-08T16:17:44Z"}
{"level":"info","msg":"Initializing new client","source":"sarama","time":"2020-11-08T16:17:44Z"}
{"level":"info","msg":"client/metadata fetching metadata for all topics from broker <KAFKA_URL>:9071\n","source":"sarama","time":"2020-11-08T16:17:44Z"}
{"level":"info","msg":"Connected to broker at <KAFKA_URL>:9071 (unregistered)\n","source":"sarama","time":"2020-11-08T16:17:44Z"}
{"level":"info","msg":"client/metadata got error from broker -1 while fetching metadata: EOF\n","source":"sarama","time":"2020-11-08T16:17:45Z"}
{"level":"info","msg":"Closed connection to broker <KAFKA_URL>:9071\n","source":"sarama","time":"2020-11-08T16:17:45Z"}
{"level":"info","msg":"client/metadata no available broker to send metadata request to","source":"sarama","time":"2020-11-08T16:17:45Z"}
{"level":"info","msg":"client/brokers resurrecting 1 dead seed brokers","source":"sarama","time":"2020-11-08T16:17:45Z"}
{"level":"info","msg":"client/metadata retrying after 250ms... (3 attempts remaining)\n","source":"sarama","time":"2020-11-08T16:17:45Z"}
{"level":"info","msg":"client/metadata fetching metadata for all topics from broker <KAFKA_URL>:9071\n","source":"sarama","time":"2020-11-08T16:17:45Z"}
{"level":"info","msg":"Connected to broker at <KAFKA_URL>:9071 (unregistered)\n","source":"sarama","time":"2020-11-08T16:17:45Z"}
{"level":"info","msg":"client/metadata got error from broker -1 while fetching metadata: EOF\n","source":"sarama","time":"2020-11-08T16:17:45Z"}
{"level":"info","msg":"Closed connection to broker <KAFKA_URL>:9071\n","source":"sarama","time":"2020-11-08T16:17:45Z"}
{"level":"info","msg":"client/metadata no available broker to send metadata request to","source":"sarama","time":"2020-11-08T16:17:45Z"}
{"level":"info","msg":"client/brokers resurrecting 1 dead seed brokers","source":"sarama","time":"2020-11-08T16:17:45Z"}
{"level":"info","msg":"client/metadata retrying after 250ms... (2 attempts remaining)\n","source":"sarama","time":"2020-11-08T16:17:45Z"}
{"level":"info","msg":"client/metadata fetching metadata for all topics from broker <KAFKA_URL>:9071\n","source":"sarama","time":"2020-11-08T16:17:45Z"}
{"level":"info","msg":"Connected to broker at <KAFKA_URL>:9071 (unregistered)\n","source":"sarama","time":"2020-11-08T16:17:45Z"}
{"level":"info","msg":"client/metadata got error from broker -1 while fetching metadata: EOF\n","source":"sarama","time":"2020-11-08T16:17:46Z"}
{"level":"info","msg":"Closed connection to broker <KAFKA_URL>:9071\n","source":"sarama","time":"2020-11-08T16:17:46Z"}
{"level":"info","msg":"client/metadata no available broker to send metadata request to","source":"sarama","time":"2020-11-08T16:17:46Z"}
{"level":"info","msg":"client/brokers resurrecting 1 dead seed brokers","source":"sarama","time":"2020-11-08T16:17:46Z"}
{"level":"info","msg":"client/metadata retrying after 250ms... (1 attempts remaining)\n","source":"sarama","time":"2020-11-08T16:17:46Z"}
{"level":"info","msg":"client/metadata fetching metadata for all topics from broker <KAFKA_URL>:9071\n","source":"sarama","time":"2020-11-08T16:17:46Z"}
{"level":"info","msg":"Connected to broker at <KAFKA_URL>:9071 (unregistered)\n","source":"sarama","time":"2020-11-08T16:17:46Z"}
{"level":"info","msg":"client/metadata got error from broker -1 while fetching metadata: EOF\n","source":"sarama","time":"2020-11-08T16:17:46Z"}
{"level":"info","msg":"Closed connection to broker <KAFKA_URL>:9071\n","source":"sarama","time":"2020-11-08T16:17:46Z"}
{"level":"info","msg":"client/metadata no available broker to send metadata request to","source":"sarama","time":"2020-11-08T16:17:46Z"}
{"level":"info","msg":"client/brokers resurrecting 1 dead seed brokers","source":"sarama","time":"2020-11-08T16:17:46Z"}
{"level":"info","msg":"Closing Client","source":"sarama","time":"2020-11-08T16:17:46Z"}
{"address":"<KAFKA_URL>:9071","level":"panic","module":"cluster","msg":"failed to start client","reason":"kafka: client has run out of available brokers to talk to (Is your cluster reachable?)","time":"2020-11-08T16:17:46Z"}
panic: (*logrus.Entry) 0xc00011b5e0

goroutine 1 [running]:
github.com/sirupsen/logrus.Entry.log(0xc0000fca10, 0xc0001214d0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/entry.go:259 +0x345
github.com/sirupsen/logrus.(*Entry).Log(0xc00011b570, 0x0, 0xc00022b718, 0x1, 0x1)
	/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/entry.go:287 +0xf0
github.com/sirupsen/logrus.(*Entry).Logf(0xc00011b570, 0xc000000000, 0xafa9b7, 0x16, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/entry.go:333 +0xe5
github.com/sirupsen/logrus.(*Entry).Panicf(...)
	/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/entry.go:371
github.com/google-cloud-tools/kafka-minion/kafka.NewCluster(0xc0003041a0, 0xc000308180, 0xc000308180)
	/app/kafka/cluster.go:82 +0x913
main.main()
	/app/main.go:53 +0x2cb
```

**Comment by weeco** [comment]
Hi @kanuahs ,
can you try to toggle `KAFKA_SASL_USE_HANDSHAKE` ? The default is set to true.

What SASL mechanism do you use?

**Comment by kanuahs** [comment]
Thanks, I tried setting `KAFKA_SASL_USE_HANDSHAKE` to false but it didn't seem to change anything. The mechanism is `SASL_PLAINTEXT` and other services can connect to that kafka cluster using [confluent-kafka-go](https://github.com/confluentinc/confluent-kafka-go).

Here are the logs:
Kafka
```
[INFO] 2020-11-24 18:00:40,036 [data-plane-kafka-network-thread-0-ListenerName(INTERNAL)-SASL_PLAINTEXT-2] org.apache.kafka.common.network.Selector pollSelectionKeys - [SocketServer brokerId=0] Failed authentication with /10.0.32.42 (Unexpected Kafka request of type METADATA during SASL handshake.)
[INFO] 2020-11-24 18:00:40,958 [data-plane-kafka-network-thread-0-ListenerName(INTERNAL)-SASL_PLAINTEXT-3] org.apache.kafka.common.network.Selector pollSelectionKeys - [SocketServer brokerId=0] Failed authentication with /10.0.32.42 (Unexpected Kafka request of type METADATA during SASL handshake.)
[INFO] 2020-11-24 18:00:41,652 [data-plane-kafka-network-thread-0-ListenerName(INTERNAL)-SASL_PLAINTEXT-0] org.apache.kafka.common.network.Selector pollSelectionKeys - [SocketServer brokerId=0] Failed authentication with /10.0.32.42 (Unexpected Kafka request of type METADATA during SASL handshake.)
[INFO] 2020-11-24 18:00:42,280 [data-plane-kafka-network-thread-0-ListenerName(INTERNAL)-SASL_PLAINTEXT-1] org.apache.kafka.common.network.Selector pollSelectionKeys - [SocketServer brokerId=0] Failed authentication with /10.0.32.42 (Unexpected Kafka request of type METADATA during SASL handshake.)
72020-11-24T18:00:53.078+0000: 48243.661: [GC pause (G1 Evacuation Pause) (young), 0.0244687 secs]
```

Kafka-minion
```

{"level":"info","msg":"Starting kafka minion version1.0.2","time":"2020-11-24T18:02:04Z"}
{"level":"debug","msg":"Sarama client config has been created successfully","time":"2020-11-24T18:02:04Z"}
{"address":"<KAFKA_BROKER_1>:9071,<KAFKA_BROKER_2>:9071","level":"info","module":"cluster","msg":"connecting to kafka cluster","time":"2020-11-24T18:02:04Z"}
{"level":"info","msg":"Initializing new client","source":"sarama","time":"2020-11-24T18:02:04Z"}
{"level":"info","msg":"client/metadata fetching metadata for all topics from broker <KAFKA_BROKER_1>:9071\n","source":"sarama","time":"2020-11-24T18:02:04Z"}
{"level":"info","msg":"Connected to broker at <KAFKA_BROKER_1>:9071 (unregistered)\n","source":"sarama","time":"2020-11-24T18:02:04Z"}
{"level":"info","msg":"client/metadata got error from broker -1 while fetching metadata: EOF\n","source":"sarama","time":"2020-11-24T18:02:04Z"}
{"level":"info","msg":"Closed connection to broker <KAFKA_BROKER_1>:9071\n","source":"sarama","time":"2020-11-24T18:02:04Z"}
{"level":"info","msg":"client/metadata fetching metadata for all topics from broker <KAFKA_BROKER_2>:9071\n","source":"sarama","time":"2020-11-24T18:02:04Z"}
{"level":"info","msg":"Connected to broker at <KAFKA_BROKER_2>:9071 (unregistered)\n","source":"sarama","time":"2020-11-24T18:02:04Z"}
{"level":"info","msg":"client/metadata got error from broker -1 while fetching metadata: EOF\n","source":"sarama","time":"2020-11-24T18:02:04Z"}
{"level":"info","msg":"Closed connection to broker <KAFKA_BROKER_2>:9071\n","source":"sarama","time":"2020-11-24T18:02:04Z"}
{"level":"info","msg":"client/metadata no available broker to send metadata request to","source":"sarama","time":"2020-11-24T18:02:04Z"}
{"level":"info","msg":"client/brokers resurrecting 2 dead seed brokers","source":"sarama","time":"2020-11-24T18:02:04Z"}
{"level":"info","msg":"client/metadata retrying after 250ms... (3 attempts remaining)\n","source":"sarama","time":"2020-11-24T18:02:04Z"}
{"level":"info","msg":"client/metadata fetching metadata for all topics from broker <KAFKA_BROKER_1>:9071\n","source":"sarama","time":"2020-11-24T18:02:04Z"}
{"level":"info","msg":"Connected to broker at <KAFKA_BROKER_1>:9071 (unregistered)\n","source":"sarama","time":"2020-11-24T18:02:04Z"}
{"level":"info","msg":"client/metadata got error from broker -1 while fetching metadata: EOF\n","source":"sarama","time":"2020-11-24T18:02:05Z"}
{"level":"info","msg":"Closed connection to broker <KAFKA_BROKER_1>:9071\n","source":"sarama","time":"2020-11-24T18:02:05Z"}
{"level":"info","msg":"client/metadata fetching metadata for all topics from broker <KAFKA_BROKER_2>:9071\n","source":"sarama","time":"2020-11-24T18:02:05Z"}
{"level":"info","msg":"Connected to broker at <KAFKA_BROKER_2>:9071 (unregistered)\n","source":"sarama","time":"2020-11-24T18:02:05Z"}
{"level":"info","msg":"client/metadata got error from broker -1 while fetching metadata: EOF\n","source":"sarama","time":"2020-11-24T18:02:05Z"}
{"level":"info","msg":"Closed connection to broker <KAFKA_BROKER_2>:9071\n","source":"sarama","time":"2020-11-24T18:02:05Z"}
{"level":"info","msg":"client/metadata no available broker to send metadata request to","source":"sarama","time":"2020-11-24T18:02:05Z"}
{"level":"info","msg":"client/brokers resurrecting 2 dead seed brokers","source":"sarama","time":"2020-11-24T18:02:05Z"}
{"level":"info","msg":"client/metadata retrying after 250ms... (2 attempts remaining)\n","source":"sarama","time":"2020-11-24T18:02:05Z"}
{"level":"info","msg":"client/metadata fetching metadata for all topics from broker <KAFKA_BROKER_1>:9071\n","source":"sarama","time":"2020-11-24T18:02:05Z"}
{"level":"info","msg":"Connected to broker at <KAFKA_BROKER_1>:9071 (unregistered)\n","source":"sarama","time":"2020-11-24T18:02:05Z"}
{"level":"info","msg":"client/metadata got error from broker -1 while fetching metadata: EOF\n","source":"sarama","time":"2020-11-24T18:02:05Z"}
{"level":"info","msg":"Closed connection to broker <KAFKA_BROKER_1>:9071\n","source":"sarama","time":"2020-11-24T18:02:05Z"}
{"level":"info","msg":"client/metadata fetching metadata for all topics from broker <KAFKA_BROKER_2>:9071\n","source":"sarama","time":"2020-11-24T18:02:05Z"}
{"level":"info","msg":"Connected to broker at <KAFKA_BROKER_2>:9071 (unregistered)\n","source":"sarama","time":"2020-11-24T18:02:05Z"}
{"level":"info","msg":"client/metadata got error from broker -1 while fetching metadata: EOF\n","source":"sarama","time":"2020-11-24T18:02:05Z"}
{"level":"info","msg":"Closed connection to broker <KAFKA_BROKER_2>:9071\n","source":"sarama","time":"2020-11-24T18:02:05Z"}
{"level":"info","msg":"client/metadata no available broker to send metadata request to","source":"sarama","time":"2020-11-24T18:02:05Z"}
{"level":"info","msg":"client/brokers resurrecting 2 dead seed brokers","source":"sarama","time":"2020-11-24T18:02:05Z"}
{"level":"info","msg":"client/metadata retrying after 250ms... (1 attempts remaining)\n","source":"sarama","time":"2020-11-24T18:02:05Z"}
{"level":"info","msg":"client/metadata fetching metadata for all topics from broker <KAFKA_BROKER_1>:9071\n","source":"sarama","time":"2020-11-24T18:02:05Z"}
{"level":"info","msg":"Connected to broker at <KAFKA_BROKER_1>:9071 (unregistered)\n","source":"sarama","time":"2020-11-24T18:02:05Z"}
{"level":"info","msg":"client/metadata got error from broker -1 while fetching metadata: EOF\n","source":"sarama","time":"2020-11-24T18:02:06Z"}
{"level":"info","msg":"Closed connection to broker <KAFKA_BROKER_1>:9071\n","source":"sarama","time":"2020-11-24T18:02:06Z"}
{"level":"info","msg":"client/metadata fetching metadata for all topics from broker <KAFKA_BROKER_2>:9071\n","source":"sarama","time":"2020-11-24T18:02:06Z"}
{"level":"info","msg":"Connected to broker at <KAFKA_BROKER_2>:9071 (unregistered)\n","source":"sarama","time":"2020-11-24T18:02:06Z"}
{"level":"info","msg":"client/metadata got error from broker -1 while fetching metadata: EOF\n","source":"sarama","time":"2020-11-24T18:02:06Z"}
{"level":"info","msg":"Closed connection to broker <KAFKA_BROKER_2>:9071\n","source":"sarama","time":"2020-11-24T18:02:06Z"}
{"level":"info","msg":"client/metadata no available broker to send metadata request to","source":"sarama","time":"2020-11-24T18:02:06Z"}
{"level":"info","msg":"client/brokers resurrecting 2 dead seed brokers","source":"sarama","time":"2020-11-24T18:02:06Z"}
{"level":"info","msg":"Closing Client","source":"sarama","time":"2020-11-24T18:02:06Z"}
{"address":"<KAFKA_BROKER_1>:9071,<KAFKA_BROKER_2>:9071","level":"panic","module":"cluster","msg":"failed to start client","reason":"kafka: client has run out of available brokers to talk to (Is your cluster reachable?)","time":"2020-11-24T18:02:06Z"}
panic: (*logrus.Entry) 0xc0003aa310

goroutine 1 [running]:
github.com/sirupsen/logrus.Entry.log(0xc000194a10, 0xc000384540, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/entry.go:259 +0x345
github.com/sirupsen/logrus.(*Entry).Log(0xc0003aa2a0, 0x0, 0xc0000ab718, 0x1, 0x1)
	/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/entry.go:287 +0xf0
github.com/sirupsen/logrus.(*Entry).Logf(0xc0003aa2a0, 0xc000000000, 0xafa9b7, 0x16, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/entry.go:333 +0xe5
github.com/sirupsen/logrus.(*Entry).Panicf(...)
	/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/entry.go:371
github.com/google-cloud-tools/kafka-minion/kafka.NewCluster(0xc0000964e0, 0xc0000803c0, 0xc0000803c0)
	/app/kafka/cluster.go:82 +0x913
main.main()
	/app/main.go:53 +0x2cb
```

**Comment by weeco** [comment]
@kanuahs Can you share all environment variables you have set and redact the sensitive values?

**Comment by kanuahs** [comment]
This is the deployment template I'm using. Generated using [this helm chart.](https://github.com/cloudworkz/kafka-minion-helm-chart). Do you want me to exec into the pod and fetch all environment variables? I can fetch those in a few hours if needed.
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-minion
  namespace: "infra"
  labels:
    app.kubernetes.io/name: kafka-minion
    helm.sh/chart: kafka-minion-1.3.0
    app.kubernetes.io/instance: kafka-minion
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kafka-minion
      app.kubernetes.io/instance: kafka-minion
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
      labels:
        app.kubernetes.io/name: kafka-minion
        app.kubernetes.io/instance: kafka-minion
    spec:
      serviceAccountName: default
      securityContext:
        
        fsGroup: 99
        runAsUser: 99
      volumes:
      containers:
        - name: kafka-minion
          image: "quay.io/google-cloud-tools/kafka-minion:v1.0.2"
          imagePullPolicy: IfNotPresent
          volumeMounts:
          env:
            - name: TELEMETRY_HOST
              value: "0.0.0.0"
            - name: TELEMETRY_PORT
              value: "8080"
            - name: EXPORTER_IGNORE_SYSTEM_TOPICS
              value: "true"
            - name: METRICS_PREFIX
              value: "kafka_minion"
            - name: LOG_LEVEL
              value: "debug"
            - name: KAFKA_BROKERS
              value: "<KAFKA_URL_1>:9071,<KAFKA_URL_2>:9071"
            - name: KAFKA_CONSUMER_OFFSETS_TOPIC_NAME
              value: "__consumer_offsets"
            - name: KAFKA_SASL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: "kafka-minion-sasl"
                  key: username
            - name: KAFKA_SASL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "kafka-minion-sasl"
                  key: password
            - name: KAFKA_SASL_USE_HANDSHAKE
              value: "false"
            - name: KAFKA_TLS_ENABLED
              value: "false"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            httpGet:
              path: /healthcheck
              port: http
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 60
            httpGet:
              path: /readycheck
              port: http
          resources:
            {}

```

**Comment by weeco** [comment]
you need to explicitly enable sasl if you use the plain mechanism. It defaults to no SASL authentication and therefore your provided username and password will not be used at all.

**Comment by kanuahs** [comment]
Oh alright. Sorry for the late update. I added the following environment variable to the `deployment.yaml` in the Helm chart and that fixed this issue.
```
- name: KAFKA_SASL_ENABLED
  value: {{ .Values.kafka.sasl.enabled | quote }}
```

Thank you! Closing this issue. I can create an issue or send a PR on the Helm chart repo if you want.
